### ISSUE TITLE
No DeepSleep after Start/Restart

### ISSUE THREAD

**Issue by derKief** [bq/aquaris-X5-plus#1]
with new ROM version 2.1.0 there is a bug with deepsleep after device start/restart.
If device is started/restarted and not unlocked immediately afterwards it doenst go into deepsleep.
This is the exact same issue/bug as [U Plus device has ](https://github.com/bq/aquaris-U-Plus/issues/1)with newest ROM 2.2.0
So this is not device specific and was no problem with previous versions.

![bbs_nodeepsleep](https://user-images.githubusercontent.com/30367720/28498117-3f63806a-6f97-11e7-9dae-f12c5b39694a.jpg)

**Comment by Kra1o5** [comment]
Hi @derKief,

Thanks for contacting us.

We are sorry, you can contact our support team through this link: https://www.bq.com/en/support/ and will attend your query as soon as possible.

Regards,

**Comment by derKief** [comment]
outdated
